### ISSUE TITLE
Rows are resorted in strange way in some cases 

### ISSUE THREAD

**Issue by zelima** [datahq/assembler#100]
While original data is sorted Eg by dates, sometimes we have cases when processed data is resorted in a strange way, to be exact one of the 2 rows are swapped. For example, take a look at this dataset https://datahub.io/datahq/datahub-kpis and one of it's graphs https://datahub.io/datahq/datahub-kpis/view/7

## Acceptance Criteria

* [ ] We know the reason behind this
* [ ] Bug is eliminated (if related to us)

## Tasks

* [ ] investigate reason
* [ ] create test case if possible 
* [ ] Fix

## Analysis 

Looking at the data prepared for rendering it does not seem to be the backend problem as it is sorted normally. Eg: Looking at this dataset https://datahub.io/datahq/datahub-kpis/v/76

* Both graph and table have `2018-05-24` before `2018-05-24`
  * ![image](https://user-images.githubusercontent.com/15143785/41344160-7dd87740-6f11-11e8-842b-6da2a71d2cf9.png)
  * ![image](https://user-images.githubusercontent.com/15143785/41344272-b6c5c12a-6f11-11e8-85ad-53249ff49e4f.png)

* Both are using the data from the resource called `premium-data-funnel-weekly`
* `premium-data-funnel-weekly` itself is sorted normally 
  * direct link https://pkgstore.datahub.io/datahq/datahub-kpis/premium-data-funnel-weekly/archive/8cac6fd79a148525b1c876809a9a4485/premium-data-funnel-weekly.csv
 * "R" link: https://datahub.io/datahq/datahub-kpis/r/premium-data-funnel-weekly.csv?v=76

As a conlusion think this is not the backend problem, but maybe the bug of a parsing library Eg tranformin CSV --> list in frontend

**Comment by anuveyatsu** [comment]
@zelima OK, I agree it must be a problem in the frontend. I will move this issue to the 'frontend' repo.

**Comment by anuveyatsu** [comment]
Issue moved to [datahq/frontend #299](https://github.com/datahq/frontend/issues/299) via [**ZenHub**](https://www.zenhub.com/)
