### ISSUE TITLE
Preview large datasets

### ISSUE THREAD

**Issue by zelima** [datahq/assembler#16]
As a Publisher I want to upload a 50Mb CSV and have the showcase page work

## Acceptance criteria 

* [x] We have preview version of all resources 

## Tasks

* [x] read refactored code and understand how it works
* [x] add new custom processor that will iteration stop at 10000 (in any case - even data is < 50mb) #23 
  * Number should be configurable. Also this should come from the views right - doesn't 
* [x] add new custum processor that will modify dp.json and add views #23 
* [x] add new Processing node for Preview in `basic_nodes.py` #22 
* [x] update `node_collector.py` with new processing node
* [x] refactore `load_modified_resources.py` to handle dp.json with views 

## analysis 

We will need two new processors: generate_views (for adding the views) and one that just takes derived resources (json) and yields only first 10000 rows.

Modifications for basic_nodes.py:

```
class DerivedFormatProcessingNode(BaseProcessingNode):

  def get_artifacts(self):
    for artifact in self.available_artifacts:
      if artifact.datahub_type == 'derived/json':  #or csv
        datahub_type = 'derived/preview' 
        resource_name = artifact.resource_name + '_preview.json'
        output = ProcessingArtifact(
        datahub_type, resource_name,
        [artifact], [],
        [(new processors + old goes here)],
                True
            )
            yield output

class DerivedPreviewProcessingNode(...):
  def __init__(self):
    ... # (all same)
```

Inside `node_collector.py` we will have to add `DerivedPreviewrocessingNode` in the appropriate order. (should come after derived json as it is depended on that)

And we will have to modify `load_modified_resources.py` to handle "views" as the views are not yet supported there.

Example datapackage.json after running pipelines:
```javascript=
{
  "resources": [
    {
      "name": "vix-daily",
      "path": "data/vix-daily.csv",
      "format": "csv",
      "mediatype": "text/csv",
      "schema": {...}
    },
    {}, // derived csv
    {}, // derived json
    { // even though json data we have a table schema
      "name": "vix-daily_csv_preview",
      "path": "data/preview/vix-daily.json",
      "datahub": {
        "derivedFrom": [
          "vix-daily_csv"
        ],
        "forView": [
          "datahub-preview-vix-daily_csv_preview"
        ],
        "type": "derived/preview" // data will be json ...
      }
    }
  ],
  "views": [
    {
      "name": "graph",
      "title": "VIX - CBOE Volatility Index",
      "specType": "simple",
      "spec": {
        "type": "line",
        "group": "Date",
        "series": [
          "VIXClose"
        ]
      }
    },
    {
      name: 'datahub-preview-vix-daily_csv_preview',
      specType: 'table',
      datahub: {
        type: 'preview'
      },
      transform: {
        limit: 10000
      },
      resources: [
        'vix-daily_csv_preview'
      ]
    }
  ]
}
```

**Comment by zelima** [comment]
FIXED
