### ISSUE TITLE
Export datapackage to zip

### ISSUE THREAD

**Issue by zelima** [datahq/assembler#19]
We need to export data into a zip if requested

## Acceptance criteria 

* [x] There is zip file on S3 

## Tasks

* [x] do analysis
* [x] grab all derived + source + non-tabular (if exists) resources in one dp.json
  * [x] Allow loading of derived non-streamed dependencies - fixed in https://github.com/datahq/assembler/commit/b3c8593e47a3c9b75781a02b2e9c2aa0aa2b8e07
* [x] Split the non-tabular node to generate one item per resource, so we can have them in dp.json #40   
* [x] zip in temp directory 
  * [x] find the way how to zip in temp directory and not have pipeline always dirty (as tmpdir is always new)
* [x] processor for setting correct paths to resources
  * [x] Find the way to set `dpp:streamedFrom` property to absolute path of the resource like it is done in `load_modified_resources` https://github.com/datahq/assembler/blob/master/datapackage_pipelines_assembler/processors/load_modified_resources.py#L41
* [x] add zip as another resource 
  * [x] processor to erase reources from dp.json of zip

## Analysis 

What we want to be zipped? - We have several different options:
* Only original source (may be broken csv, json etc..)
* Only good data (derived csv, json, etc...)
* Original data + good data (derived csv, json etc...)

How should datapackage.json look like?

* Has relative paths for resources
* Has URL for resources
* Both?
* What about zip itself? it is one of the resources, and should be included in dp.json that will be exported on S3, but zip itself needs dp.json that includes all the resources to zip them

What about other output formats? Eg sqlite - should it be zipped if both present?

---

If zip occurred as kind in source-pec we should append new processor `dump.to_zip` to the pipeline, after add it as resource and export to s3.

Available parameter(s):
out-file: optional #defaults to {dataset-name}.zip

## Spec for source

```yaml=
meta:
  owner: <owner username>
  ownerid: <owner unique id>
  dataset: <dataset name>
  version: 1
  findability: <published/unlisted/private>
inputs:
  - 
    kind: datapackage
    url: <datapackage-url>
    parameters:
      resource-mapping:
        <resource-name-or-path>: <resource-url>
outputs:
  -
    kind: zip
    parameter: 
       out-file:: my path
```

**Comment by zelima** [comment]
FIXED. First dataset with zip output http://datahub.io/zelima1/vix-zip-testing#resource-dataset_zip
This actually took more than 40 hours to be implemented.
