### ISSUE TITLE
Processors for getting preview

### ISSUE THREAD

**Issue by zelima** [datahq/assembler#23]
We need two new processors to be able to have preview resources - processors for getting first N rows from given resource and processor for adding views to the `datapackage.json`

parameters: limit (will default to 10000)

# Acceptance Criteria

* [x] after the processors run we have sperate resource with only N number of rows

# Tasks

* [x] add processors that yields only N (or 10000) rows
* [x] add processors that creates (or modifies) views
* [x] tests

**Comment by zelima** [comment]
FIXED
