### ISSUE TITLE
Why pkgstore URL's have ":" in the middle rather than "/"

### ISSUE THREAD

**Issue by zelima** [datahq/assembler#26]
If you take a look at the paths of the resources in the datapakcage.json they look like this: "https://pkgstore.datahub.io/core/finance-vix:non-tabular/data/vix-daily.csv"

The structure on the S3 is the same:

```
| pkgstore.datahub.io
--| core
--|--| finance-vix:non-tabular
--|--|--| data
--|--|--|--| vix-daily.csv
```

@akariv Is this done on purpose or there should be `/` and that is a bug? 
Example dp.json: https://pkgstore.datahub.io/core/finance-vix/latest/datapackage.json

## Acceptance criteria

* [ ] we know the reason why it is there
* [ ] if that is a bug repalce with `/`

## Tasks

* [ ] investigate reason 
* [ ] fix if neccssary 
* [ ] rerun assembler

**Comment by akariv** [comment]
Yes, this is on purpose - it takes after the name of the pipeline.
Once we store files on S3 based on their hash, this will be gone.
