### ISSUE TITLE
Deal with generating first/last XXX rows for preview resources 

### ISSUE THREAD

**Issue by zelima** [datahq/assembler#39]
how we are going to deal with sorting data that is time sensitive. Eg: for Finance Vix, that is updated daily, we need last 200 rows (or maybe first for other datasets), to display the latest data

# Acceptance Criteria

* [ ] we have latest data for preview 

# Tasks

* [ ] List possible solutions
* [ ] Choose best for us
* [ ] implement

## Analysis

* One solution for this would be including some info in views Eg: `{desc: true/false}`
* Another option would be to include that info inside `processing` object of source-spec

cc @rufuspollock and @akariv what do you think about this?

**Comment by rufuspollock** [comment]
@zelima my instinct is we do simplest thing possible for now for previews which is first XXX rows. Later on we will support proper transformations and those will take care of that but for now simple solution is fine.

**Comment by zelima** [comment]
INVALID as discussed this is not relevant for now and even after it is does not belong to this service (repo)
