### ISSUE TITLE
[EPIC] Maintaining and improving Quality of Factory

### ISSUE THREAD

**Issue by zelima** [datahq/assembler#45]
As a developer I want to have whole system under test so that whenever I make new changes I am sure that nothing else is broken.

As a product owner I want to be sure that site will work fine before some new feature is launched to production, so that our users have a good experience

As a developer I want to be able to add new features quickly which means e.g. I don't have to worry I've broken other stuff or do manual testing on the site all the time so that our users get new features faster

## Acceptance criteria

* [x] Black box tests for the website covering:
* [x] Input/output tests for assembler + dpp so that we have good coverage, avoid regressions and can quickly debug problems
* [x] Unit tests for assembler
* [x] deploy to testing first and test there before deployed to production (once a day?)
  

## Tasks

* [x] Black box tests for assembler + pipelines - #48 
* [x] Don’t auto-redeploy containers on production #50 
* [x] Run black box tests on testing constantly #51 
* [x] redeploy production if all is fine in testing (if nesssarry)

## Analysis

* Research how to split auto-redeploy for testing and production envs on docker
  * https://docs.docker.com/docker-cloud/builds/automated-build/

**Comment by zelima** [comment]
FIXED
