### ISSUE TITLE
[EPIC] Event store so that we can measure statistical quality of factory and frontend

### ISSUE THREAD

**Issue by zelima** [datahq/assembler#46]
As an admin, I want to record most activities (sign up, sign in, push etc) so that I'm know how frequently users are using platform and how often they achieve expected results

As a Publisher, I want to see what has happened recently with my data (and in future what my team has done) so that I know things are working, what's changed etc

As a Viewer I want to see what a Publisher has been up to so that I know whether they are active, what's new and what's hot (so that ...)

## Acceptance Criteria

* [ ] We have easily measurable statistics

## Tasks

* [ ] Report events to ES: WHO did WHAT WHEN #52 
  * [ ] do analysis how to gather needed info
  * [ ] do analysis how to put this on elastic search 
* [ ] Record push completion (always successful)
* [ ] Display push completion in dashboard (?)
* [ ] Record push fail
* [ ] Record push start
* [ ] Record ...
* [ ] Write blog post about new dashboard

## Analysis

In order to do statistical analyses we need to record most possible activities on the platform. Good place for storing info would be the elastic search

What are the events?

* **[Flow] Push completed [assembler]**
  * Success / Failure
* Dataset created (special case of push - where push is a new dataset) [spec store?]
* [Flow] Push started (time elapsed to success can be ca) [assembler]
* Download (clicks, GET on data file) [Google Analytics] 
* User sign up (happens through out system)
* (?) User sign in to frontend (?) (happens through our system)
* (Page view) [Google Analytics]
  * Search of term [Google Analytics]

### Design of the ES index

```
{
  "timestamp": ...
  // type of event
  "event_entity": "flow|account|..."
  "event_action": "create/finished/deleted/...
  // event filters
  "owner": ...
  "dataset": ... // may not always be there ...
  // results
  "outcome": "ok/error", or "status": "good/bad/ugly",
  "messsage": ... // mostly blank
  "findability": ...
  "payload": {
    // anything you want add - customizing the event info per object
    flow-id (aka pipeline-id)
  }
}
```

```
{
  "timestamp":
  "owner":
  "payload": ...
}
```

### Desired Queries

For user dashboard:

SELECT * FROM events where event.owner = userid SORT DESC timestamp;

SELECT * FROM events where ... AND 

For user public profile

SELECT * FROM events where event.owner = profilid AND findability == 'public' AND type != 'login'

Internally

SELECT count(*) FROM events where type = "dataset/push" AND outcome == "failed" 

### Collection

* should a collection of data happen daily, or on every event?
  * Depends on where we are getting data from but preferably on every event (push style). For some external data e.g. downloads we may need to pull on a regular basis.
* How to automate this?
* how to gather as they are split across different services/API?

**Comment by zelima** [comment]
Issue moved to [datahq/pm #43](https://github.com/datahq/pm/issues/43) via [**ZenHub**](https://www.zenhub.com/)
