### ISSUE TITLE
Black box tests for assembler + pipelines

### ISSUE THREAD

**Issue by zelima** [datahq/assembler#48]
## Acceptance criteria

* [ ] covers most cases of spec - regular, remote, zip, etc...

## Tasks

* [ ] Choose a few sample flow specs that we want to always work
* [ ] Run them as part of the test suite using dpp
* [ ] Verify the outputs

**Comment by zelima** [comment]
FIXED
