### ISSUE TITLE
Black box tests for the website

### ISSUE THREAD

**Issue by zelima** [datahq/assembler#49]
## Acceptance croteria

* [ ] page with views, without views, large, small, (non-tabular?)  are tested

## Tasks

* [ ] Choose a few pages that we want to always work
* [ ] Verify that pages load in a reasonable time
  * homepage -  < 1sec
  * showcase page - < 15 sec
* [ ] Verify that download links work
* [ ] Verify that downloaded data makes sense
* [ ] Verify that views appear correctly

**Comment by zelima** [comment]
DUPLICATE of https://github.com/datahq/pm/issues/42
