### ISSUE TITLE
Pretty print datapackage.json 

### ISSUE THREAD

**Issue by zelima** [datahq/assembler#54]
As a user, I want to see datapackage.json prettified other than have it on one line, so that it is easy for me to read it

## Acceptance Criteria

* [ ] datapackage,json is pretty printed 

## Tasks 

* [ ] explore code where json resources are generated
* [ ] refactor to write prettified version  of json
