### ISSUE TITLE
Put events on Elastic Search

### ISSUE THREAD

**Issue by zelima** [datahq/assembler#55]
Besides metadata, we want to store events on Elastic Search

## Acceptance Criteria

* [ ] able to query the existing Elastic Search Eg: with Kibana for now (later with API) and get successful push events 

## Tasks

* [x] create new index "events"
* [x] for now save only sucsessfull executions
* [x] Design index in the following way 
```
{
  "timestamp": ...
  // type of event
  "event_entity": "flow|account|..."
  "event_action": "create/finished/deleted/...
  // event filters
  "owner": ...
  "dataset": ... // may not always be there ...
  // results
  "outcome": "ok/error", or "status": "good/bad/ugly",
  "messsage": ... // mostly blank
  "findability": ...
  "payload": {
    // anything you want add - customizing the event info per object
    flow-id (aka pipeline-id)
  }
}
```

**Comment by zelima** [comment]
FIXED
