### ISSUE TITLE
 generator to read pipelines from the flowmanager db.

### ISSUE THREAD

**Issue by zelima** [datahq/assembler#60]
Currently, we are using SourceSpecRegistry to read from DB what pipelines need to be run.  Since we extracted planning part of assembling and changed the flow management,  SourceSpecRegistry is not useful anymore. 

## Acceptance Criteria 

* [ ] generator reads from new db and runs pipelines accordingly 

## Tasks

* [ ] use FlowManager as dependency and query the DB
* [ ] integrate with BB tests

**Comment by zelima** [comment]
FIXED
