### ISSUE TITLE
Test for granular output types

### ISSUE THREAD

**Issue by zelima** [datahq/assembler#64]
@zelima commented on [Thu Nov 09 2017](https://github.com/datahq/specstore/issues/13)

Depending on config passed to planner we have a different kind of outputs. We need to test all of them

## Acceptance Criteria

* [ ] tested most of the possible outputs

## Tasks
* [ ] produces a datapackage.json (does nothing) - (keeps original resources)
  * Planner that does basically nothing - just does the datapackage.json copy across ...
* [ ] produces just (derived) csv
* [ ] produces csv, json
* [ ] produces csv, json, preview
* [ ] produces csv, json, preview, zip

**Comment by zelima** [comment]
FIXED
