### ISSUE TITLE
Files in Exported zip files are placed in "hash" folders

### ISSUE THREAD

**Issue by zelima** [datahq/assembler#65]
If you try and download zip files, data inside is placed in following structure 
```
|- data/data.csv
|- data/filehash1/data_csv.csv
|- data/filehash2/data_json.csv
|- datapackage.json
```
We don't need hashes 

## Acceptance Criteria

* [x] no "hash folders" inside zip

## Tasks

* [x] create new processor that removes hashes form file paths
* [x] update planner to run that processor before `dump.to_zip` in `outputNodes`

**Comment by zelima** [comment]
FIXED
