### ISSUE TITLE
Boot up specstore service for Black Box tests

### ISSUE THREAD

**Issue by zelima** [datahq/assembler#70]
We moved from exporting events via `dump.to_index` the processor at the end of the pipelines, to hitting specstore api after all pipelines are executed. Since assembler bb tests do not include specstore API, the tests that include checking events index is now failing.

## Acceptance criteria

* [x] No failing bb tests 

## Tasks

* [x] comment the tests checking `events` index
* [x] boot up specstore api For travis 
* [x] comment out lines commented above

**Comment by zelima** [comment]
FIXED
