### ISSUE TITLE
New pipeline with goodtables validation

### ISSUE THREAD

**Issue by zelima** [datahq/assembler#71]
We want to add a new pipeline which runs goodtables validation on each source of the pipeline.
* Result is a json report, stored as a non-tabular resource in the datapackage
* Failure to validate doesn’t fail the pipeline!

## Acceptance Criteria

* [x] there is non-tabular resource on S3 named datapackage_report

## Tasks

* [x] analysis 
* [x] new processor for validation
* [x] adapt planner to use new collector https://github.com/datahq/planner/issues/7
* [x] test processor
* [x] update bb tests

## Analysis

* Create new processor `validate_source` that runs Goodtables validation and returns JSON (prob [goodtables](https://github.com/frictionlessdata/goodtables-py#report) report)
```
parameters, datapackage, res_iter = ingest()

report_name = 'datapackage_report.json'

def generate_report(datapackage_):
    reports = []
    dp = Package(datapackage_)

    for resource in dp.resources:
        report = validate(
            resource.descriptor[PROP_STREAMED_FROM],
            preset='datapackage',
            schema=resource.descriptor,
        )
        reports.append(report)
    f = open(report_name, 'w')
    json.dump(reports, f)

generate_report(datapackage)

dp_report = {
    'name': datapackage['name']+'-report',
    'resources': [{
        PROP_STREAMED_FROM: report_name,
        'name': 'datapackage_report',
        'format': 'json',
        'path': 'data/datapackage_report.json',
        'datahub': {
          'type': "derived/report",
        },
        'description': 'Validation report for tabular data'
    }]
}


spew(dp_report, [])
```
* Create new ReportProcessingNode with the following processors:
* `ReportProcessingNode` will come first in node collector

**Comment by zelima** [comment]
FIXED
