### ISSUE TITLE
Data Validation pipeline always returns valid report 

### ISSUE THREAD

**Issue by zelima** [datahq/assembler#74]
Currently no matter how data is invalid validation report always returns `valid: true`

## Acceptance criteria

* [x] Report should say that data is invalid
* [x] Report should contain list of errors init

## Tasks 

* [x] add failing test fir invalid report
* [x] debug

**Comment by zelima** [comment]
FIXED. 
Reason: for some reasons if preset was set to `datapckage` goodtables were always returning `valid=true` with warning `could not load path/to/my.csv`

Now instead of `datapacage` we use `table` as preset and pass the options (resource descriptor) to the `validate` method with small change - if `skip_rows` is set to be integer (for tabulator) we modify it to be list
