### ISSUE TITLE
Datapackage contains Invalid zipped file with 'csv' extension, when there is zipped source.

### ISSUE THREAD

**Issue by AcckiyGerman** [datahq/assembler#78]
As a user I want to have a source file with a right extension, so I could open it.

## Acceptance criteria
Clone https://github.com/datasets/eu-emissions-trading-system repo and do `data push-flow`
Go on the datapackage page on the datahub.io, wait for processing and download the result data-package archive.

Inside the archive you should find:
* [ ] source zip file with proper extension

OR
* [ ] unzipped source csv file

## Tasks
* [ ] find the place, where the source file is saved into datapackage
* [ ] write the test
* [ ] fix method

## Analysis

When processing zipped source the `resource_name.csv` file appears in an output data-package, which is actually not `csv` but a `zip` file. The customers could be confused.

Bug was met here:
https://testing.datahub.io/AcckiyGerman/eu-emissions-trading-system  
The wrong file is inside this archive: https://testing.datahub.io/AcckiyGerman/eu-emissions-trading-system/r/eu-emissions-trading-system_zip.zip  

Probably you cant open this page, if you are not AcckiyGerman, so here is the github and a public datahub links:
https://github.com/datasets/eu-emissions-trading-system
https://datahub.io/core/eu-emissions-trading-system

**Comment by zelima** [comment]
Ok, so this took me a while, but finally got it. The problem is in the descriptor itself: The extension to the file is `.csv` while it should be `.zip`. Since the tabulator does no really care the extension and just extracts and process the file we were not getting any errors and data looked fine as well. But since the original files are just copied and added to archive with the original names it was just sitting there with wrong extension.

I've modified the dp.json of `eu-emissions-trading-system` and re-pushed https://github.com/datasets/eu-emissions-trading-system/commit/9b85e2b5291600e9ea0789fc60216a17882d096b. so now everything is fine https://datahub.io/core/eu-emissions-trading-system/v/12

Closing as FIXED
