### ISSUE TITLE
datapackage.json in zip file differs from version on github or pkgstore.datahub.io

### ISSUE THREAD

**Issue by zelima** [datahq/assembler#81]
Originally comes from here https://github.com/datahq/datahub-qa/issues/41

> As discussed on gitter, the version of datapackage.json included in zip files downloaded from datahub.io lack basic metadata like title, license, description.
See a diff here between https://pkgstore.datahub.io/core/registry/6/datapackage.json (left hand side) and the version included in the zip file downloaded (right hand side): http://www.mergely.com/Xo9fTlfZ/

## Acceptance Criteria

* [ ] datapackage.json in zip containt key metadata about dataset

## Task 

* [ ] investigate why they are different 
* [ ] update if neccessary 

## Analysis 

**Reason:** This is happening cause zip is just another derived resource and its metadata is created from the scratch - not loaded from the original one. Same way is done for any other resource and besides key metadata each datapackage.json has it's own name Eg for the datapackage.json on the right side of the screen name is ` "name": "registry_zip",` - names are aligned with resources they are derived from. 

**Solution:** We can load metadata from original datapackage.json instead of [creating it from the scratch](https://github.com/datahq/planner/blob/master/planner/nodes/planner.py#L131) and this info will be common for all derived resources including zip. Meaning **All** derived resources have datapackage.json with exactly same metadata but different resources inside

Problem with above is that dp.json will include unnecessary  stuff like views and README

**Comment by zelima** [comment]
FIXED. Will be live as soon as we re-push
