### ISSUE TITLE
Fix the  build 

### ISSUE THREAD

**Issue by zelima** [datahq/assembler#83]
Due to recent changes in Auth service, specstore need it to be booted up to not fail. Current build is on Travis failing cause of that.

## Acceptance Criteria

* [ ] build is fine 

## Tasks

* [ ] boot-up auth service locally
* [ ] run the tests and pass 
* [ ] run auth server on travis 
* [ ] pass the tests

**Comment by zelima** [comment]
FIXED
