### ISSUE TITLE
Include hash for derived/report

### ISSUE THREAD

**Issue by zelima** [datahq/assembler#88]
Currently, the hash of the file is not included as a part of metadata of deriver/report resource. Eg https://s3.amazonaws.com/pkgstore.datahub.io/a08d3588fbae0355042537595c65819d/airport-codes/68/datapackage.json

Besides we have resource without hash, this results zipped dataset to have "hash" folder init https://datahub.io/core/airport-codes/r/airport-codes_zip.zip

## Acceptance Criteria

* [ ] Hash is included in resource meta
* [ ] No "hash" folder in zip 

## Tasks

* [ ] tests
* [ ] calculate hash in `generate_report` processor and include it
