### ISSUE TITLE
Processor for extracting README for zip 

### ISSUE THREAD

**Issue by zelima** [datahq/assembler#91]
Originally coming from https://github.com/datahq/datahub-qa/issues/129

Currently, zipped dataset does not contain README (except in the dp.json). We need it in the main directory.  To accomplish that we need a simple processor that extracts README from dp.js as a single file. And place this processor before `dump.to_zip` in planner 

## Acceptance Criteria

* [ ] zip files have README in it
* [ ] processor is tested 

## Tasks

* [ ] tests
* [ ] add new processor 
* [ ] update planner
