### ISSUE TITLE
Processor to update metadata for source

### ISSUE THREAD

**Issue by zelima** [datahq/assembler#93]
We need to deal with to things

* Keep the original source file init - and not clean, processed by `tabulator`. Eg removed rows, unpivoted etc...
* place source files int the archive/directory

To accomplish above we need to change current behaviour, that simply coppies source data from `rawstore` to `pkgstore`, and update with metadata before this is done.  Meaning we will be able to include have hash for it, size, set path on demand etc..  This way we will have all the files in zipped dataset in nice structured way, meaning data get will get in same structure + we don't lose original data

## Acceptance Criteria

* [x] source data includes hash and all necessary meta.
* [x] In zip resource we have it placed under `archive/` dir
* [x] we have original data

## Tasks 

* [x] introduce `update_source` processors
* [x] update tests 
* [x] intorduce `deduplicate_resources` processor
* [x] update planner appropriately 

## Analysis 

While developing it occurred that inside zip resource we have duplicated source files. This was happening cause source file is added twice - 1 at the begging (to start the process. Does not present in the `node_collectors` ) and one another at the end (the one that is in the `node_collectors`). So I introduced another processor `deduplicate_resources` that just filters resources with duplicated names

**Comment by zelima** [comment]
FIXED/INVALID we decided to introduce another resource with `original` type that will have a path to `archive/resource-name.ext` So no need of this processors for now
